version: '3'

services:
  back:
    image: node
    entrypoint: 'npm run start_local'
    working_dir: /usr/src/app
    volumes:
      - '~/Documentos/projetos/git/dom-gilittus/backjs:/usr/src/app'
    ports:
      - '8081:8080'

  front:
    image: node
    working_dir: /usr/src/app
    volumes:
      - '~/Documentos/projetos/git/dom-gilittus/front:/usr/src/app' # caminho do projeto frontend
    ports:
      - '8080:8080'
    entrypoint: 'npm run serve'
